#pragma once

#include "EpdFontData.h"

// 1-bit UI CJK: every ideograph in Noto Sans JP, plus kana, punctuation,
// and simplified-Chinese UI characters the JP face does not cover.
// Latin stays in the Ubuntu UI face. Regenerated by tools/gen_ui_jp_font.py.
extern const EpdFontData jp_12;
