#pragma once

#include "EpdFontData.h"

// 1-bit UI CJK: Jōyō kanji + kana + CJK punctuation + extra UI ideographs (zh).
// Latin stays in the Ubuntu UI face. Regenerated by tools/gen_ui_jp_font.py.
extern const EpdFontData jp_12;
