#!/usr/bin/env python3
"""Rasterize Jōyō kanji + kana + extra UI CJK into a 1-bit EpdFont.

Matches Ubuntu 12: 12 pt at 150 DPI (~25 px). Latin is left to Ubuntu.
Extra ideographs are taken from on-device UI strings (Chinese copy).

Example:
    .venv/bin/python tools/gen_ui_jp_font.py \\
        --ttf lib/EpdFont/fontsrc/NotoSansJP-Medium.otf \\
        --joyo tools/joyo_kanji.txt \\
        --extra src/core/UiText.h \\
        --fallback-ttf lib/EpdFont/fontsrc/NotoSansSC-Medium.otf \\
        -o lib/EpdFont/builtinFonts/jp_12.cpp
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

# Same as fontconvert.py for ubuntu_12_*.
PT = 12
DPI = 150

# UI CJK besides Jōyō: punctuation, hiragana, katakana, fullwidth, halfwidth kana.
RANGES = [
    (0x3000, 0x303F),
    (0x3041, 0x3096),
    (0x3099, 0x309F),
    (0x30A0, 0x30FF),
    (0xFF01, 0xFF5E),
    (0xFF61, 0xFF9F),
]


def fp4_from_26_6(val: int) -> int:
    return (val + 2) >> 2


def pack_mono(buffer: bytes, width: int, height: int, pitch: int) -> bytes:
    if width <= 0 or height <= 0:
        return b""
    out = bytearray()
    acc = 0
    n = 0
    src_pitch = abs(pitch)
    for y in range(height):
        row = y * src_pitch
        for x in range(width):
            src_byte = buffer[row + (x >> 3)]
            bit = (src_byte >> (7 - (x & 7))) & 1
            acc = (acc << 1) | bit
            n += 1
            if n == 8:
                out.append(acc)
                acc = 0
                n = 0
    if n:
        acc <<= 8 - n
        out.append(acc)
    return bytes(out)


def merge_intervals(cps: list[int]) -> list[tuple[int, int]]:
    if not cps:
        return []
    ordered = sorted(set(cps))
    out: list[tuple[int, int]] = []
    start = prev = ordered[0]
    for cp in ordered[1:]:
        if cp == prev + 1:
            prev = cp
            continue
        out.append((start, prev))
        start = prev = cp
    out.append((start, prev))
    return out


def chunks(data: bytes, n: int):
    for i in range(0, len(data), n):
        yield data[i : i + n]


def is_cjk_ideograph(cp: int) -> bool:
    return 0x4E00 <= cp <= 0x9FFF or 0x3400 <= cp <= 0x4DBF or 0xF900 <= cp <= 0xFAFF


def load_joyo(path: Path) -> list[int]:
    text = path.read_text(encoding="utf-8")
    cps: list[int] = []
    for ch in text:
        cp = ord(ch)
        if is_cjk_ideograph(cp):
            cps.append(cp)
    return cps


def load_extra_cps(paths: list[Path]) -> list[int]:
    cps: set[int] = set()
    for path in paths:
        text = path.read_text(encoding="utf-8")
        for ch in text:
            cp = ord(ch)
            if is_cjk_ideograph(cp):
                cps.add(cp)
    return sorted(cps)


def collect_cps(joyo: list[int], extra: list[int]) -> list[int]:
    cps = set(joyo)
    cps.update(extra)
    for a, b in RANGES:
        for cp in range(a, b + 1):
            cps.add(cp)
    return sorted(cps)


def emit_cpp(path: Path, glyphs: list[tuple], intervals: list[tuple[int, int, int]], bitmaps: bytes, metrics: tuple[int, int, int]) -> None:
    advance_y, ascender, descender = metrics
    lines: list[str] = []
    lines.append("/**")
    lines.append(" * generated by tools/gen_ui_jp_font.py")
    lines.append(" * name: jp_12")
    lines.append(" * size: 12 pt @ 150 DPI, 1-bit mono")
    lines.append(f" * glyphs: {len(glyphs)}  bitmap: {len(bitmaps)} bytes")
    lines.append(" */")
    lines.append('#include "builtinFonts/jp_12.h"')
    lines.append("")
    lines.append(f"static const uint8_t jp_12Bitmaps[{len(bitmaps)}] = {{")
    for chunk in chunks(bitmaps, 16):
        lines.append("    " + " ".join(f"0x{b:02X}," for b in chunk))
    lines.append("};")
    lines.append("")
    lines.append("static const EpdGlyph jp_12Glyphs[] = {")
    for g in glyphs:
        width, height, advance, left, top, length, offset, cp = g
        lines.append(
            f"    {{ {width}, {height}, {advance}, {left}, {top}, {length}, {offset} }}, // U+{cp:04X}"
        )
    lines.append("};")
    lines.append("")
    lines.append("static const EpdUnicodeInterval jp_12Intervals[] = {")
    for first, last, offset in intervals:
        lines.append(f"    {{ 0x{first:X}, 0x{last:X}, 0x{offset:X} }},")
    lines.append("};")
    lines.append("")
    lines.append("const EpdFontData jp_12 = {")
    lines.append("    jp_12Bitmaps,")
    lines.append("    jp_12Glyphs,")
    lines.append("    jp_12Intervals,")
    lines.append(f"    {len(intervals)},")
    lines.append(f"    {advance_y},")
    lines.append(f"    {ascender},")
    lines.append(f"    {descender},")
    lines.append("    false,")
    lines.append("    nullptr,")
    lines.append("    0,")
    lines.append("    nullptr,")
    lines.append("    nullptr,")
    lines.append("    nullptr,")
    lines.append("    nullptr,")
    lines.append("    0,")
    lines.append("    0,")
    lines.append("    0,")
    lines.append("    0,")
    lines.append("    nullptr,")
    lines.append("    0,")
    lines.append("};")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ttf", required=True, help="Noto Sans JP (or other CJK) TTF/OTF")
    ap.add_argument("--joyo", default="tools/joyo_kanji.txt", help="UTF-8 Jōyō kanji list")
    ap.add_argument(
        "--extra",
        action="append",
        default=[],
        help="UTF-8 source to scan for extra UI CJK (repeatable)",
    )
    ap.add_argument(
        "--fallback-ttf",
        default="lib/EpdFont/fontsrc/NotoSansSC-Medium.otf",
        help="OTF/TTF used for extra UI CJK missing from --ttf (Noto Sans SC)",
    )
    ap.add_argument("-o", "--output", default="lib/EpdFont/builtinFonts/jp_12.cpp")
    args = ap.parse_args()

    import freetype

    ttf = Path(args.ttf)
    joyo_path = Path(args.joyo)
    if not ttf.is_file():
        print(f"missing font: {ttf}", file=sys.stderr)
        return 1
    if not joyo_path.is_file():
        print(f"missing joyo list: {joyo_path}", file=sys.stderr)
        return 1

    joyo = load_joyo(joyo_path)
    if len(joyo) != 2136:
        print(f"warning: expected 2136 Jōyō kanji, got {len(joyo)}", file=sys.stderr)

    extra_paths = [Path(p) for p in args.extra] or [Path("src/core/UiText.h")]
    for path in extra_paths:
        if not path.is_file():
            print(f"missing extra source: {path}", file=sys.stderr)
            return 1
    extra = load_extra_cps(extra_paths)
    extra_only = [cp for cp in extra if cp not in set(joyo)]

    face = freetype.Face(str(ttf))
    face.set_char_size(PT << 6, PT << 6, DPI, DPI)
    fallback = None
    fallback_path = Path(args.fallback_ttf) if args.fallback_ttf else None
    if fallback_path and fallback_path.is_file():
        fallback = freetype.Face(str(fallback_path))
        fallback.set_char_size(PT << 6, PT << 6, DPI, DPI)
        print(f"fallback font: {fallback_path}", file=sys.stderr)
    load_flags = freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO | freetype.FT_LOAD_FORCE_AUTOHINT

    wanted = collect_cps(joyo, extra)
    present: list[int] = []
    missing_joyo: list[int] = []
    missing_extra: list[int] = []
    joyo_set = set(joyo)
    extra_set = set(extra_only)
    faces_for_cp: dict[int, object] = {}
    for cp in wanted:
        src = face if face.get_char_index(cp) != 0 else None
        if src is None and fallback is not None and fallback.get_char_index(cp) != 0:
            src = fallback
        if src is None:
            if cp in joyo_set:
                missing_joyo.append(cp)
            elif cp in extra_set:
                missing_extra.append(cp)
            continue
        faces_for_cp[cp] = src
        present.append(cp)
    if missing_joyo:
        print(f"error: font missing {len(missing_joyo)} Jōyō kanji, e.g. U+{missing_joyo[0]:04X}", file=sys.stderr)
        return 1
    if missing_extra:
        sample = " ".join(f"U+{cp:04X}" for cp in missing_extra[:8])
        print(f"error: font missing {len(missing_extra)} extra UI CJK, e.g. {sample}", file=sys.stderr)
        return 1

    glyphs = []
    blob = bytearray()
    for cp in present:
        src = faces_for_cp[cp]
        gi = src.get_char_index(cp)
        src.load_glyph(gi, load_flags)
        glyph = src.glyph
        bitmap = glyph.bitmap
        packed = pack_mono(bytes(bitmap.buffer), bitmap.width, bitmap.rows, bitmap.pitch)
        advance = fp4_from_26_6(glyph.advance.x)
        if advance < 0:
            advance = 0
        if advance > 0xFFFF:
            advance = 0xFFFF
        glyphs.append(
            (
                bitmap.width,
                bitmap.rows,
                advance,
                glyph.bitmap_left,
                glyph.bitmap_top,
                len(packed),
                len(blob),
                cp,
            )
        )
        blob.extend(packed)

    merged = merge_intervals(present)
    offset = 0
    intervals = []
    for first, last in merged:
        intervals.append((first, last, offset))
        offset += last - first + 1

    metrics = (
        int(math.ceil(face.size.height / 64.0)),
        int(math.ceil(face.size.ascender / 64.0)),
        int(math.floor(face.size.descender / 64.0)),
    )

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    emit_cpp(out, glyphs, intervals, bytes(blob), metrics)
    print(
        f"Wrote {out}  {out.stat().st_size / 1024:.1f} KB source  "
        f"glyphs={len(glyphs)} extra_ui={len(extra_only)} bitmap={len(blob)} intervals={len(intervals)} "
        f"advanceY={metrics[0]} ascender={metrics[1]} descender={metrics[2]}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
